import {
  Stethoscope,
  Home,
  Car,
  GraduationCap,
  Scissors,
  Dumbbell,
  Laptop,
  Scale,
  DollarSign,
  Sparkles,
  Wrench,
  Users,
  Heart,
  Cog,
  Palette,
  Shirt,
  Code,
  Building,
  Megaphone,
  Camera,
  Languages,
  Briefcase,
  Calendar,
  Sofa,
  PenTool,
  Music,
  Plane
} from "lucide-react";

export const iconMap: { [key: string]: any } = {
  'Sparkles': Sparkles,
  'Wrench': Wrench,
  'Heart': Heart,
  'Dumbbell': Dumbbell,
  'Scissors': Scissors,
  'GraduationCap': GraduationCap,
  'Stethoscope': Stethoscope,
  'Home': Home,
  'Car': Car,
  'Laptop': Laptop,
  'Scale': Scale,
  'DollarSign': DollarSign,
  'Users': Users,
  'Cog': Cog,
  'Palette': Palette,
  'Shirt': Shirt,
  'Code': Code,
  'Building': Building,
  'Megaphone': Megaphone,
  'Camera': Camera,
  'Languages': Languages,
  'Briefcase': Briefcase,
  'Calendar': Calendar,
  'Sofa': Sofa,
  'PenTool': PenTool,
  'Music': Music,
  'Plane': Plane
};

export const colorMap: { [key: string]: { text: string; bg: string } } = {
  'blue': { text: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-950/20' },
  'orange': { text: 'text-orange-500', bg: 'bg-orange-50 dark:bg-orange-950/20' },
  'red': { text: 'text-red-500', bg: 'bg-red-50 dark:bg-red-950/20' },
  'green': { text: 'text-green-500', bg: 'bg-green-50 dark:bg-green-950/20' },
  'pink': { text: 'text-pink-500', bg: 'bg-pink-50 dark:bg-pink-950/20' },
  'purple': { text: 'text-purple-500', bg: 'bg-purple-50 dark:bg-purple-950/20' },
  'slate': { text: 'text-slate-500', bg: 'bg-slate-50 dark:bg-slate-950/20' },
  'gray': { text: 'text-gray-500', bg: 'bg-gray-50 dark:bg-gray-950/20' },
};
