// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ggmlplgksoswahntuoed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbWxwbGdrc29zd2FobnR1b2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODA0NTMsImV4cCI6MjA3MzQ1NjQ1M30.XvHJ4GIkligzfF26kJTHJC3Flram4QB7fEEXmE5XCeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});